apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1   # ✅ change from 2 to 1 (you have 1 node)
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tradingacr.azurecr.io/frontend:latest
        ports:
        - containerPort: 80
